# Use when training on complex data such as free text or when achieving
# maximum downstream accuracy for ML tasks is a goal.
#
# We use a higher RNN to better learn the structures with a tradeoff
# in longer training and generation times.

schema_version: "1.0"
name: "complex-or-free-text"
models:
  - synthetics:
      data_source: "__tmp__"
      params:
        epochs: 100
        vocab_size: 20000
        learning_rate: .001
        rnn_units: 1024
        batch_size: 256
