# Data with a record count of > 250K and 
# column count of > 20

# Customize privacy filters https://docs.gretel.ai/gretel.ai/synthetics/synthetics-faqs/privacy-protection

schema_version: "1.0"
name: "high-dimensionality-high-record-count"
models:
  - ctgan:
        data_source: __tmp__
        params:
            epochs: 100
            generator_dim: [1024, 1024]
            discriminator_dim: [1024, 1024]
            generator_lr: 0.0001
            discriminator_lr: .00033
            batch_size: 1000
        # Gretel privacy filtering
        privacy_filters:
            outliers: null
            similarity: auto
