# deprecated: This configuration will be deprecated soon. Please use the "synthetics/tabular-lstm" configuration.

schema_version: "1.0"
name: "high-accuracy"
models:
  - synthetics:
      data_source: __tmp__
      params:
        epochs: 100
        vocab_size: 0
        learning_rate: .001
        rnn_units: 256
        batch_size: 64
      generate:
        num_records: 5000
      privacy_filters:
        outliers: null
        similarity: null
