# Data with a record count of > 50K or 
# highly dimensional data. 

schema_version: "1.0"
name: "high-dimensionality"
models:
  - ctgan:
        data_source: __tmp__
        params:
            epochs: 600
            generator_dim: [1024, 1024]
            discriminator_dim: [1024, 1024]
            generator_lr: 0.0001
            discriminator_lr: .00033
            batch_size: 600
        privacy_filters:
            outliers: null
            similarity: auto
