# For datasets that have a low number of records, in the hundreds or so.

# Customize privacy filters https://docs.gretel.ai/gretel.ai/synthetics/synthetics-faqs/privacy-protection

schema_version: "1.0"
name: "low-record-count"
models:
  - ctgan:
        data_source: __tmp__
        params:
            epochs: 600
            generator_dim: [1024, 1024]
            discriminator_dim: [1024, 1024]
            generator_lr: 0.0001
            discriminator_lr: .00033
            batch_size: 600
        # Gretel privacy filtering
        privacy_filters:
            outliers: auto
            similarity: auto
