# deprecated: This configuration will be deprecated soon. Please use the "synthetics/tabular-actgan" configuration.

schema_version: "1.0"
name: "low-record-count"
models:
  - actgan:
        data_source: __tmp__
        params:
            epochs: auto
            generator_dim: [1024, 1024]
            discriminator_dim: [1024, 1024]
            generator_lr: 0.0001
            discriminator_lr: .00033
            batch_size: auto
        generate:
            num_records: 5000
        privacy_filters:
            outliers: auto
            similarity: auto
