# When training on natural language data such as reviews, tweets, and conversations

# If training data contains multiple columns, specify the column containing natural language text
# using the column_name parameter

schema_version: "1.0"
name: "natural-language-gpt"
models:
  - gpt_x:
      data_source: "__temp__"
      pretrained_model: 'EleutherAI/gpt-neo-125M'
      batch_size: 4
      epochs: 3
      weight_decay: 0.01
      warmup_steps: 100
      lr_scheduler: "linear"
      learning_rate: 0.0002
      column_name: null
      generate:
        num_records: 10
