schema_version: 1.0
name: "navigator_ft-dp"
models:
- navigator_ft:
    data_source: __tmp__

    # Optionally group records by the column(s) set below.
    # This is useful if you need to maintain correlations
    # across multiple records. Otherwise, the training
    # assumes records are independent.
    group_training_examples_by: null

    # Optionally order records by the column set below.
    # This is useful if your records are sequential.
    # Note that this parameter can only be used when
    # your records are grouped using the above parameter.
    order_training_examples_by: null

    generate:
        num_records: 5000

        # With DP, enabling structured generation can help with
        # increasing the percentage of valid records.
        use_structured_generation: true

    params:
        num_input_records_to_sample: auto

        # You can try increasing this until you run out-of-memory.
        batch_size: 8

    privacy_params:
        dp: true

        # Defines the privacy budget - the larger the value, the 
        # less privacy we get. A value between 2 and 8 is deemed
        # reasonable, usually.
        epsilon: 8
