# Template for generating synthetic data, then evaluating it on classification or regression models

# You can change the params for evaluation by following instructions in the comments below
# IMPORTANT: make sure to add in the name of the "target" (label or prediction) column in the parameters below

schema_version: "1.0"
name: "synthetic-evaluate"
models:
  # This configuration uses the Gretel Long Short Term Memory (LSTM) model to generate synthetic data. 
  # You can use any synthetic model configuration. For example, to use Gretel ACTGAN model, copy over the configuration from "tabular-actgan.yml"
  - synthetics:
      data_source: __tmp__
      params:
        epochs: auto
        vocab_size: auto
        learning_rate: auto
        batch_size: auto
        rnn_units: auto
      generate:
        num_records: 5000
      privacy_filters:
        outliers: auto
        similarity: auto
      evaluate:
        task: classification # or "regression"
        target: "MY_TARGET_COLUMN"              ########### IMPORTANT! RENAME TO THE LABEL/PREDICTION COLUMN NAME OF YOUR DATA ###########
        # holdout: 0.2                          # Default train-test split  
        # metric: "acc"                         # Default metric for classification is accuracy, for regression is R-squared. See docs for all metrics available.
        # models: ["knn", ..., "xgboost"]       # Default models used are all models available in the library. See docs to use a subset of models.
