# Default configuration template for generating synthetic data, then evaluating it on classification/regression

# In this example configuration, we use the default config for Gretel Long Short Term Memory (LSTM) Model to generate synthetic data
# but you can substitute any synthetics model (like Gretel ACTGAN for high-dimensional data or DGAN for time-series data)

# We also indicate parameters for evaluating classification, but you can also change the params to evaluate data on regression models by following the comments
# Make sure to indicate what your target column is named 

schema_version: "1.0"
name: "synthetic-evaluate"
models:
  # The following is the default configuration for Gretel LSTM model to generate synthetic data. 
  # You can use any synthetic model configuration. For example, to use GRETEL ACTGAN, copy over the default configuration from "tabular-actgan.yml"
  - synthetics:
      data_source: __tmp__
      params:
        epochs: auto
        vocab_size: auto
        learning_rate: auto
        batch_size: auto
        rnn_units: auto
      generate:
        num_records: 5000
      privacy_filters:
        outliers: auto
        similarity: auto
      # These parameters add evaluation for classification. To evaluate your data on regression models, change the configuration as instructed
      evaluate:
        task: classification # or "regression"  ###### To evaluate regression, change the task to "regression"
        target: "MY_TARGET_COLUMN"              ###### Change this string to reflect the header for the label/prediction column of your data
        # holdout: 0.2                          
        # metric: "acc"
        # models: ["knn", ..., "xgboost"]
