# Default configuration for Synthetic model creation using Gretel's Long Short Term Memory (LSTM) Model

schema_version: "1.0"
name: "default-config"
models:
  - synthetics:
      data_source: __tmp__
      params:
        epochs: auto
        vocab_size: auto
        learning_rate: auto
        batch_size: auto
        rnn_units: auto
      generate:
        num_records: 5000
      privacy_filters:
        outliers: auto
        similarity: auto
