# Default configuration for ACTGAN.

schema_version: "1.0"
name: "tabular-actgan"
models:
  - actgan:
        data_source: __tmp__
        params:
            epochs: auto
            generator_dim: [1024, 1024]
            discriminator_dim: [1024, 1024]
            generator_lr: 0.0001
            discriminator_lr: .00033
            batch_size: auto
            auto_transform_datetimes: False
        generate:
            num_records: 1000
        privacy_filters:
            outliers: null # Set to "auto" for additional protections
            similarity: null # Set to "auto" for additional protections