# Policy to search for "sensitive PII" as defined by
# https://www.experian.com/blogs/ask-experian/what-is-personally-identifiable-information/

# Use optional label_predictors and regular expressions to define custom predictors 
# See https://docs.gretel.ai/classify/classify-model-configuration


schema_version: "1.0"
name: "classify-default"
models:
  - classify:
      data_source: "_"
      use_nlp: false
      labels:
        - person_name
        - credit_card_number
        - phone_number
        - us_social_security_number
        - email_address
        - location
