version: "2"
inputs: {}
steps:
  - name: sample-data-read
    task: data_source
    config:
      data_source: https://blueprints-dev.gretel.cloud/sample_data/clinical_notes.csv
  - name: holdout
    task: holdout
    config: {}
  - task: text_ft
    name: text_ft
    config:
      train:
        pretrained_model: TinyLlama/TinyLlama-1.1B-Chat-v1.0
        column_name: null
        params:
          batch_size: 16
          gradient_accumulation_steps: 8
          epochs: 3
          weight_decay: 0.01
          warmup_steps: 100
          lr_scheduler: linear
          learning_rate: 0.001
          max_tokens: 128
        peft_params:
          lora_r: 8
          lora_alpha_over_r: 1
        privacy_params:
          dp: true
          epsilon: 5
          delta: auto
      generate:
        num_records: 1000
        maximum_text_length: 128
  - name: evaluate
    task: evaluate_safe_synthetics_dataset
    inputs:
    - text_ft
    - holdout
    config: {}