# Policy to search for and redact "sensitive PII" as defined by `ask-experian` as well as
# a custom defined regular expression for user IDs. 
# https://www.experian.com/blogs/ask-experian/what-is-personally-identifiable-information/

schema_version: "1.0"
name: "redact-pii-nlp"
models:
  - transform_v2:
      data_source: "_"
      globals:
        classify:
          # Classification currently uses the Gretel Cloud. If you are running in a hybrid
          # environment and prefer not to use the Cloud, please set "enable: false" below.
          enable: true
          entities:
            - name
            - email
            - phone_number
            - address
            - credit_card_number
            - ssn
          ner_threshold: 0.2
        locales: [en_US, en_CA]
      steps:
        - rows:
            update:
              - condition: column.entity is in globals.classify.entities
                value: column.entity | fake
                fallback_value: '"<" ~ column.entity ~ ">"'
              - type: text
                value: this | fake_entities
