schema_version: "1.0"
name: default
task:
  name: text_ft
  config:
    train:
      pretrained_model: "gretelai/gpt-auto"
      params:
        batch_size: 4
        steps: 750
        weight_decay: 0.01
        warmup_steps: 100
        lr_scheduler: "linear"
        learning_rate: 0.0001
        max_tokens: 128
    generate:
      num_records: 1000
      maximum_text_length: 128
