name: Tests

on:
  push:
    branches:
      - '**'

jobs:
  build-manifest:
    runs-on: ubuntu-latest
    steps:

    # Setup and install deps
    - uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install deps
      run: | 
        pip install -r requirements.txt

    # Run tests first
    - name: Unit tests
      run: |
        pytest -s -vv test_config_templates.py
      env:
        GRETEL_API_KEY: ${{ secrets.GRETEL_API_KEY }}

    # job notif
    - uses: 8398a7/action-slack@v2
      with:
        status: ${{ job.status }}
        author_name: Tests, Check Manifest
        only_mention_fail: here
      env:
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
